export const DEFAULT_USD_RATE = 17800;
export const PROJECTION_YEARS = 10;

export const ASSET_CLASSES = [
  {
    id: "cash",
    name: "Cash / Bank",
    return: 1.0,
    color: "var(--color-viz-cash)",
    isEquity: false,
    isUSD: false,
    taxRate: 0.2,
    liquidity: "T+0",
    risk: "Sangat Rendah",
    defaultDrawdown: 0,
    description:
      "Uang fisik atau tabungan bank biasa. Likuid penuh, bunga rendah.",
  },
  {
    id: "bankDigital",
    name: "Bank Digital",
    return: 4.0,
    color: "var(--color-viz-digital-bank)",
    isEquity: false,
    isUSD: false,
    taxRate: 0.2,
    liquidity: "T+0",
    risk: "Sangat Rendah",
    defaultDrawdown: 0,
    description:
      "Tabungan bank digital (Blu, Jago, dst). Bunga lebih tinggi, LPS terjamin.",
  },
  {
    id: "sbn_ritel",
    name: "SBN Ritel (ORI/SR/ST/SBR)",
    description: "Surat Berharga Negara khusus ritel. Dijamin negara 100%.",
    risk: "Sangat Rendah",
    liquidity: "Rendah",
    return: 6.0,
    isEquity: false,
    taxRate: 0.10,
    color: "var(--color-viz-sbn-ritel)",
    defaultDrawdown: 3,
  },
  {
    id: "rdpu",
    name: "Reksadana Pasar Uang",
    return: 5.1,
    color: "var(--color-viz-rdpu)",
    isEquity: false,
    isUSD: false,
    taxRate: 0.1,
    liquidity: "T+1",
    risk: "Rendah",
    defaultDrawdown: 0.5,
    description: "Reksa dana pasar uang. Stabil, cocok untuk dana darurat.",
  },
  {
    id: "usd",
    name: "Valas USD",
    return: 3.5,
    color: "var(--color-viz-usd)",
    isEquity: false,
    isUSD: true,
    taxRate: 0,
    liquidity: "T+0",
    risk: "Sedang",
    defaultDrawdown: 10,
    description:
      "Simpanan USD. Return dari apresiasi kurs IDR/USD historis ~3–4%/tahun.",
  },
  {
    id: "rdpu_usd",
    name: "Reksadana Pasar Uang (USD)",
    description: "Reksa dana pasar uang berdenominasi USD. Stabil dengan return mengikuti rate The Fed.",
    risk: "Rendah",
    liquidity: "Tinggi",
    return: 4.8,
    isEquity: false,
    taxRate: 0,
    color: "var(--color-viz-rdpu-usd)",
    isUSD: false,
    defaultDrawdown: 1,
    canSwitchCurrency: true,
  },
  {
    id: "obligasi_fr",
    name: "Obligasi FR",
    description: "Obligasi negara yang dapat diperdagangkan di pasar sekunder. Risiko rendah.",
    risk: "Rendah-Menengah",
    liquidity: "Menengah",
    return: 6.5,
    isEquity: false,
    taxRate: 0.10,
    defaultDrawdown: 8,
    color: "var(--color-viz-obligasi-fr)",
  },
  {
    id: "rdo",
    name: "Reksadana Obligasi",
    return: 6.5,
    color: "var(--color-viz-bonds)",
    isEquity: false,
    isUSD: false,
    taxRate: 0.1,
    liquidity: "T+2",
    risk: "Rendah–Sedang",
    defaultDrawdown: 10,
    description: "Reksa dana obligasi. Return lebih tinggi, sedikit fluktuasi.",
  },
  {
    id: "gold",
    name: "Emas / Gold",
    return: 9.0,
    color: "var(--color-viz-gold)",
    isEquity: false,
    isUSD: false,
    taxRate: 0,
    isGold: true,
    liquidity: "T+1",
    risk: "Sedang",
    defaultDrawdown: 20,
    description:
      "Emas fisik/digital (Antam, Pegadaian, dll). Return ~9%/thn IDR. Sudah dipotong biaya efektif ~1.5%/thn (spread + PPh buyback + admin).",
  },
  {
    id: "rd_campuran",
    name: "Reksadana Campuran",
    description: "Kombinasi saham dan obligasi. Return moderat dengan risiko terukur.",
    risk: "Menengah-Tinggi",
    liquidity: "Tinggi",
    return: 8.5,
    isEquity: true,
    taxRate: 0,
    defaultDrawdown: 25,
    color: "var(--color-viz-rd-campuran)",
  },
  {
    id: "sp500",
    name: "S&P 500 ETF",
    return: 10.5,
    color: "var(--color-viz-sp500)",
    isEquity: true,
    isUSD: false,
    canSwitchCurrency: true,
    taxRate: 0.1,
    liquidity: "T+2",
    risk: "Tinggi",
    defaultDrawdown: 50,
    description:
      "Indeks saham AS. Return historis ~10% USD/tahun + estimasi apresiasi kurs IDR.",
  },
  {
    id: "rdSaham",
    name: "Reksadana Saham",
    return: 11.0,
    color: "var(--color-viz-rd-saham)",
    isEquity: true,
    isUSD: false,
    taxRate: 0,
    liquidity: "T+3",
    risk: "Tinggi",
    defaultDrawdown: 45,
    description:
      "Kumpulan saham pilihan yang dikelola oleh Manajer Investasi profesional. Diversifikasi tinggi, potensi return jangka panjang.",
  },
  {
    id: "saham",
    name: "Saham IDX",
    return: 12.0,
    color: "var(--color-viz-local-stocks)",
    isEquity: true,
    isUSD: false,
    taxRate: 0.001,
    liquidity: "T+2",
    risk: "Tinggi",
    defaultDrawdown: 60,
    description:
      "Saham IDX via LTS. Potensi return tinggi dengan volatilitas signifikan.",
  },
  {
    id: "nasdaq",
    name: "NASDAQ 100 ETF",
    description: "Indeks 100 perusahaan teknologi terbesar AS. Volatilitas tinggi.",
    risk: "Sangat Tinggi",
    liquidity: "Tinggi",
    return: 15.0,
    isEquity: true,
    taxRate: 0.10,
    color: "var(--color-viz-nasdaq)",
    isUSD: false,
    defaultDrawdown: 65,
    canSwitchCurrency: true,
  },
  {
    id: "us_stocks",
    name: "Saham US Individu",
    description: "Saham perusahaan Amerika Serikat secara spesifik (Apple, Microsoft, Tesla).",
    risk: "Sangat Tinggi",
    liquidity: "Tinggi",
    return: 12.0,
    isEquity: true,
    taxRate: 0.10,
    color: "var(--color-viz-us-stocks)",
    isUSD: false,
    defaultDrawdown: 75,
    canSwitchCurrency: true,
  },
  {
    id: "kripto",
    name: "Aset Kripto (BTC, ETH)",
    description: "Aset digital desentralisasi. Volatilitas sangat ekstrem, potensi return eksponensial.",
    risk: "Sangat Tinggi",
    liquidity: "Sangat Tinggi",
    return: 25.0,
    isEquity: true,
    taxRate: 0.0021, // Pajak kripto Indo: 0.1% PPh + 0.11% PPN
    color: "var(--color-viz-kripto)",
    isUSD: false,
    defaultDrawdown: 90,
    canSwitchCurrency: true,
  }
];
